# Generated by Django 5.0.14 on 2025-10-03 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="calendar_synced",
            field=models.BooleanField(
                default=False,
                help_text="Whether the appointment has been synced to calendar",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="confirmation_sent",
            field=models.BooleanField(
                default=False, help_text="Whether confirmation email has been sent"
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar event ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="reminder_sent",
            field=models.BooleanField(
                default=False, help_text="Whether reminder email has been sent"
            ),
        ),
    ]
