# Generated by Django 5.0.14 on 2025-10-03 02:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_appointment_calendar_synced_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Healthcare provider's full name", max_length=200
                    ),
                ),
                (
                    "specialty",
                    models.CharField(
                        choices=[
                            ("general", "General Practitioner"),
                            ("cardiology", "Cardiology"),
                            ("dermatology", "Dermatology"),
                            ("pediatrics", "Pediatrics"),
                            ("psychiatry", "Psychiatry"),
                            ("orthopedics", "Orthopedics"),
                            ("neurology", "Neurology"),
                            ("other", "Other"),
                        ],
                        default="general",
                        help_text="Provider's specialty",
                        max_length=50,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Provider's email for notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, help_text="Provider's contact phone", max_length=20
                    ),
                ),
                (
                    "consultation_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=50.0,
                        help_text="Price for consultation appointments",
                        max_digits=10,
                    ),
                ),
                (
                    "follow_up_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=30.0,
                        help_text="Price for follow-up appointments",
                        max_digits=10,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether the provider is currently accepting appointments",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Provider's biography or description"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Healthcare Provider",
                "verbose_name_plural": "Healthcare Providers",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="appointment",
            name="provider_name",
            field=models.CharField(
                blank=True,
                help_text="Legacy provider name field - will be deprecated",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="provider",
            field=models.ForeignKey(
                blank=True,
                help_text="Healthcare provider for this appointment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="appointments",
                to="appointments.provider",
            ),
        ),
    ]
